export interface PrevalenceChartByNumPathogenData {
  pathogenCode: string;
  pathogenName: string | null;
  pathogenGroupName: string;
  categoryName: string;
  grpAnalysAttrbts: string;
  allPositiveCasesCount: number;
  validCount: number;
  allPositiveCasesRate: string;
  __typename: "prevalenceNum";
}

export const chartData: PrevalenceChartByNumPathogenData[] = [
  {
    pathogenCode: "CT",
    pathogenName: "CT",
    pathogenGroupName: "CT (CGMT)",
    categoryName: "CT__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 7,
    validCount: 73,
    allPositiveCasesRate: "9.6",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "MG",
    pathogenName: "MG",
    pathogenGroupName: "MG (CGMT)",
    categoryName: "MG__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 1,
    validCount: 73,
    allPositiveCasesRate: "1.4",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "TV",
    pathogenName: "TV",
    pathogenGroupName: "TV (CGMT)",
    categoryName: "TV__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 1,
    validCount: 73,
    allPositiveCasesRate: "1.4",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "11",
    pathogenName: "11",
    pathogenGroupName: "11 (HPV28)",
    categoryName: "11__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 3,
    validCount: 172,
    allPositiveCasesRate: "1.7",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "16",
    pathogenName: "16",
    pathogenGroupName: "16 (HPV28)",
    categoryName: "16__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 14,
    validCount: 172,
    allPositiveCasesRate: "8.1",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "18",
    pathogenName: "18",
    pathogenGroupName: "18 (HPV28)",
    categoryName: "18__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 5,
    validCount: 172,
    allPositiveCasesRate: "2.9",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "31",
    pathogenName: "31",
    pathogenGroupName: "31 (HPV28)",
    categoryName: "31__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 11,
    validCount: 172,
    allPositiveCasesRate: "6.4",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "33",
    pathogenName: "33",
    pathogenGroupName: "33 (HPV28)",
    categoryName: "33__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 6,
    validCount: 172,
    allPositiveCasesRate: "3.5",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "35",
    pathogenName: "35",
    pathogenGroupName: "35 (HPV28)",
    categoryName: "35__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 2,
    validCount: 172,
    allPositiveCasesRate: "1.2",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "40",
    pathogenName: "40",
    pathogenGroupName: "40 (HPV28)",
    categoryName: "40__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 8,
    validCount: 172,
    allPositiveCasesRate: "4.7",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "42",
    pathogenName: "42",
    pathogenGroupName: "42 (HPV28)",
    categoryName: "42__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 9,
    validCount: 172,
    allPositiveCasesRate: "5.2",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "43",
    pathogenName: "43",
    pathogenGroupName: "43 (HPV28)",
    categoryName: "43__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 5,
    validCount: 172,
    allPositiveCasesRate: "2.9",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "44",
    pathogenName: "44",
    pathogenGroupName: "44 (HPV28)",
    categoryName: "44__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 3,
    validCount: 172,
    allPositiveCasesRate: "1.7",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "45",
    pathogenName: "45",
    pathogenGroupName: "45 (HPV28)",
    categoryName: "45__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 3,
    validCount: 172,
    allPositiveCasesRate: "1.7",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "51",
    pathogenName: "51",
    pathogenGroupName: "51 (HPV28)",
    categoryName: "51__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 18,
    validCount: 172,
    allPositiveCasesRate: "10.5",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "52",
    pathogenName: "52",
    pathogenGroupName: "52 (HPV28)",
    categoryName: "52__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 17,
    validCount: 172,
    allPositiveCasesRate: "9.9",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "53",
    pathogenName: "53",
    pathogenGroupName: "53 (HPV28)",
    categoryName: "53__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 16,
    validCount: 172,
    allPositiveCasesRate: "9.3",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "54",
    pathogenName: "54",
    pathogenGroupName: "54 (HPV28)",
    categoryName: "54__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 21,
    validCount: 172,
    allPositiveCasesRate: "12.2",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "56",
    pathogenName: "56",
    pathogenGroupName: "56 (HPV28)",
    categoryName: "56__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 12,
    validCount: 172,
    allPositiveCasesRate: "7.0",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "58",
    pathogenName: "58",
    pathogenGroupName: "58 (HPV28)",
    categoryName: "58__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 2,
    validCount: 172,
    allPositiveCasesRate: "1.2",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "59",
    pathogenName: "59",
    pathogenGroupName: "59 (HPV28)",
    categoryName: "59__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 12,
    validCount: 172,
    allPositiveCasesRate: "7.0",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "66",
    pathogenName: "66",
    pathogenGroupName: "66 (HPV28)",
    categoryName: "66__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 12,
    validCount: 172,
    allPositiveCasesRate: "7.0",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "68",
    pathogenName: "68",
    pathogenGroupName: "68 (HPV28)",
    categoryName: "68__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 2,
    validCount: 172,
    allPositiveCasesRate: "1.2",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "70",
    pathogenName: "70",
    pathogenGroupName: "70 (HPV28)",
    categoryName: "70__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 6,
    validCount: 172,
    allPositiveCasesRate: "3.5",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "73",
    pathogenName: "73",
    pathogenGroupName: "73 (HPV28)",
    categoryName: "73__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 3,
    validCount: 172,
    allPositiveCasesRate: "1.7",
    __typename: "prevalenceNum",
  },
  {
    pathogenCode: "82",
    pathogenName: "82",
    pathogenGroupName: "82 (HPV28)",
    categoryName: "82__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 3,
    validCount: 172,
    allPositiveCasesRate: "1.7",
    __typename: "prevalenceNum",
  },
  /* {
    pathogenCode: "Total",
    pathogenName: null,
    pathogenGroupName: "Total",
    categoryName: "__1",
    grpAnalysAttrbts: "",
    allPositiveCasesCount: 203,
    validCount: 172,
    allPositiveCasesRate: "118.0",
    __typename: "prevalenceNum",
  }, */
];
